const $ = (id) => document.getElementById(id);
const input = $('file-input'), dropzone = $('dropzone');
let toastTimer;
function toast(message) { const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove('show'),2600); }
function size(bytes) { if(bytes<1024)return `${bytes} B`; const units=['KB','MB','GB','TB']; let n=bytes/1024,i=0; while(n>=1024&&i<units.length-1){n/=1024;i++;} return `${n.toFixed(n>=100?0:1)} ${units[i]}`; }
async function api(url, options={}) { const response=await fetch(url,{credentials:'same-origin',...options}); if(response.status===401){$('pin-dialog').showModal();throw new Error('PIN required');} if(!response.ok){let message=`Request failed (${response.status})`;try{message=(await response.json()).detail||message;}catch{} throw new Error(message);} return response; }
async function refreshFiles() { const data=await (await api('/api/files')).json(); $('file-count').textContent=`${data.files.length} ${data.files.length===1?'file':'files'}`; $('empty').classList.toggle('hidden',data.files.length>0); const root=$('files');root.replaceChildren(); for(const file of data.files){const row=document.createElement('div');row.className='file-row';const icon=document.createElement('div');icon.className='file-icon';icon.textContent='▤';const info=document.createElement('div');info.className='file-info';const name=document.createElement('div');name.className='file-name';name.textContent=file.name;const sz=document.createElement('div');sz.className='file-size';sz.textContent=size(file.size);info.append(name,sz);const actions=document.createElement('div');actions.className='actions';const download=document.createElement('a');download.className='action';download.textContent='↓ Download';download.href=`/api/files/${encodeURIComponent(file.name)}`;const del=document.createElement('button');del.className='action delete';del.textContent='Delete';del.onclick=async()=>{if(!confirm(`Delete “${file.name}”?`))return;try{await api(`/api/files/${encodeURIComponent(file.name)}`,{method:'DELETE'});toast('File deleted');refreshFiles();}catch(e){toast(e.message);}};actions.append(download,del);row.append(icon,info,actions);root.append(row);}}
function upload(file){const section=$('transfer-section');section.classList.remove('hidden');const row=document.createElement('div');row.className='transfer';row.innerHTML='<div class="transfer-top"><span class="transfer-name"></span><span class="transfer-percent">0%</span></div><div class="progress"><span></span></div><div class="transfer-bottom"><span class="transfer-state">Preparing…</span><span class="transfer-speed"></span></div>';row.querySelector('.transfer-name').textContent=file.name;$('transfers').append(row);const xhr=new XMLHttpRequest();xhr.open('PUT',`/api/files/${encodeURIComponent(file.name)}`);const started=performance.now();xhr.upload.onprogress=(event)=>{if(!event.lengthComputable)return;const pct=Math.floor(event.loaded/event.total*100),elapsed=Math.max((performance.now()-started)/1000,.01),speed=event.loaded/elapsed,remaining=Math.max(event.total-event.loaded,0),eta=speed>0?Math.ceil(remaining/speed):0;row.querySelector('.transfer-percent').textContent=`${pct}%`;row.querySelector('.progress span').style.width=`${pct}%`;row.querySelector('.transfer-state').textContent=`${size(event.loaded)} of ${size(event.total)} · ${eta>0?`ETA ${eta}s`:'Finishing…'}`;row.querySelector('.transfer-speed').textContent=`${size(speed)}/s`;};xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300){row.querySelector('.transfer-percent').textContent='100%';row.querySelector('.progress span').style.width='100%';row.querySelector('.transfer-state').textContent='Upload complete';row.querySelector('.transfer-speed').textContent='';refreshFiles();}else{row.querySelector('.transfer-state').textContent=xhr.status===401?'PIN required':`Failed: ${xhr.responseText.slice(0,120)}`;row.querySelector('.transfer-percent').textContent='Error';}};xhr.onerror=()=>{row.querySelector('.transfer-state').textContent='Network error';row.querySelector('.transfer-percent').textContent='Error';};xhr.send(file);}
$('browse').onclick=()=>input.click();dropzone.onclick=(event)=>{if(event.target.id!=='browse')input.click();};dropzone.onkeydown=(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();input.click();}};input.onchange=()=>{for(const file of input.files)upload(file);input.value='';};for(const event of ['dragenter','dragover'])dropzone.addEventListener(event,(e)=>{e.preventDefault();dropzone.classList.add('dragging');});for(const event of ['dragleave','drop'])dropzone.addEventListener(event,(e)=>{e.preventDefault();dropzone.classList.remove('dragging');});dropzone.ondrop=(e)=>{for(const file of e.dataTransfer.files)upload(file);};
$('pin-form').onsubmit=async(e)=>{e.preventDefault();$('pin-error').textContent='';try{const response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:$('pin').value})});if(!response.ok)throw new Error('Incorrect PIN. Try again.');$('pin-dialog').close();$('pin').value='';init();}catch(err){$('pin-error').textContent=err.message;}};
async function init(){try{const [info,status]=await Promise.all([(await api('/api/info')).json(),(await api('/api/status')).json()]);$('network-url').textContent=info.url;$('network-url').href=info.url;$('qr').src='/api/qr.png';$('port').textContent=info.port;$('directory').textContent=info.directory;$('device-count').textContent=status.connected_devices;await refreshFiles();}catch(e){if(e.message!=='PIN required')toast(e.message);}}
init();
